version: '3'

dotenv:
  - .env.example

#tasks:
  #prepare:
    #cmd: go mod tidy

  #lint:
    #cmds:
      #- golangci-lint run ./cmd

  #test:
    #cmds:
     # - go test -cover ./cmd

  #compile:
   # cmd: GOOS=linux go build -o ./bin/goapp ./goapp

build:
  cmd: docker build --pull --rm -f './goapp/Dockerfile' -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest' '.'
    - docker build --pull --rm -f ./goapp/debianDockerfile -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}-bookworm '.'
  push:
    cmds:
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}-bookworm
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME}:latest
  deploy:
    cmd: kubectl apply -f ./godeployment.yaml

  release:
    cmds:
      #- task: prepare
      #- task: lint
      #- task: test
      #- task: compile
      - task: build
      - task: push
      - task: deploy